# Generated by Django 3.1.7 on 2021-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('too', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
