# Generated by Django 3.1.7 on 2021-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0004_tohirgoo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world', models.CharField(max_length=300)),
                ('nuugdsan', models.IntegerField()),
                ('daraalal', models.IntegerField()),
            ],
        ),
    ]
