# Generated by Django 3.1.7 on 2021-03-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0005_tses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tses',
            old_name='world',
            new_name='word',
        ),
    ]
