# Generated by Django 3.1.7 on 2021-03-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0007_rowtses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('nuugdsan', models.IntegerField()),
                ('daraalal', models.IntegerField()),
            ],
        ),
    ]
